WikiEducationFoundation/apps-android-wikiedudashboard

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/data/network/WikiEduDashboardApi.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/CampaignListRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/CampaignListContract.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/CampaignListPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/RetrofitCampaignListProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/data/CampaignListData.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/data/ExploreCampaignsResponse.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/view/CampaignListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/common/view/CourseDetailActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/home/ExploreFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/view/MediaDetailFragment.kt
- app/src/main/res/layout/fragment_campaign_list.xml
- app/src/main/res/layout/fragment_media_details.xml
- app/src/main/res/layout/item_rv_campaign_list.xml
- app/src/main/res/values/strings.xml
**Description:**
Fixes #38  (Added Campaign List following MVP architecture)
**Changes Made:**
- Added a campaign list module following MVP architecture. 
- Used recyclerview for showing list for campaigns.
> Added Campaign List following MVP architecture

- .travis.yml
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/view/CampaignListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/view/CourseListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/view/MyDashboardFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/home/ExploreFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/home/HomeActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/GlideImageLoader.java
- app/src/main/res/layout/fragment_explore.xml
- app/src/main/res/menu/menu_explore.xml
- app/src/main/res/values/strings.xml
**Description:**
Fixes #43 and #7 
- SearchView added in Explore Fragment
- added method to update data in recyclerview according to search query. 
**Screenshots**
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
> Search feature added in active courses, campaigns

- app/build.gradle
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/data/preferences/SharedPrefs.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/CampaignListPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/view/CampaignListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/presenter/ArticlesEditedPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/provider/RetrofitArticlesEditedProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/view/CourseArticlesEditedFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/common/provider/RetrofitCourseDetailProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/RecentActivityFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/RecentActivityPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/RetrofitRecentActivityProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/provider/RetrofitStudentListProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/view/StudentListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/provider/RetrofitCourseUploadsProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/view/CourseUploadsFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/presenter/CourseListPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/view/CourseListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/MyDashboardPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/view/MyDashboardFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/home/ExploreFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/MediaDetailsPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/view/MediaDetailFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/ProfilePresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/RetrofitProfileProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileCourseListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/welcome/OutreachProgramsDashboardFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/welcome/WikiEducationDashboardFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/ViewUtils.kt
> Add timber as logging module

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileStatsFragment.kt
- app/src/main/res/layout/fragment_profile_stats.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
> Display message when user is not enrolled in any course

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/view/MyDashboardFragment.kt
> Prevent app from crashing when search icon is clicked

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/home/HomeActivity.kt
> Use proper colours for text and hint text in SearchView

- app/src/main/res/layout/activity_splash.xml
> Use constraint layout in activity_splash.xml

- app/src/main/res/layout/app_bar_main.xml
- app/src/main/res/layout/fragment_my_dashboard.xml
> Use constraint layout in app_bar_main.xml

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/view/CampaignListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/view/CourseArticlesEditedFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/RecentActivityFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/view/StudentListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/view/CourseUploadsFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/view/CourseListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/view/MyDashboardFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/view/MediaDetailFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileCourseListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/settings/SettingsActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/ViewUtils.kt
Removed the `singleton` from `ViewUtils`, and I replaced by kotlin extension function.
> #87 Replace singleton utils with kotlin extension function

- app/src/main/res/layout/activity_course_detail.xml
- app/src/main/res/layout/activity_settings.xml
This xml file have been changed to use constraintLayout
> activity_settings.xml

- app/src/main/res/layout/activity_media_detail.xml
> Fixes #65 Use constraint layout in activity_media_details.xml

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/CategoryListRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/CourseListRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/CourseUploadsRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/FileUsesRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/CampaignListPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/RetrofitCampaignListProvider.kt
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/apps-android-wikiedudashboard/blob/master/CONTRIBUTING.md#pull-request-process
Documented classes
- CampaignListPresenterImpl.kt
- CategoryListRecyclerAdapter.kt
- CourseListRecyclerAdapter.kt
- CourseUploadsRecyclerAdapter.kt
- FileUsesRecyclerAdapter.kt
- RetrofitCampaignListProvider.kt
Just learned how to synchronize forked project from the upstream project, not sure if this will still get conflicts
> code documenting 2

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/data/network/ProviderUtils.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/data/preferences/SharedPrefs.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/ArticlesEditedRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/CampaignListRecyclerAdapter.kt
- Added KDoc to ProviderUtils.kt, SharedPrefs.kt, ArticlesEditedRecyclerAdapter.kt, and CampaignListRecyclerAdapter.kt
> First try of Kotlin documenting

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/MyDashboardRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/ProfileCourseListRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/RecentActivityRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/StudentListRecyclerAdapter.kt
issue #80 
Documented classes:
- MyDashboardRecyclerAdapter.kt
- ProfileCourseListRecyclerAdapter
- RecentActivityRecyclerAdapter
- StudentListRecyclerAdapter
> 4 classes documented

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/data/CampaignListData.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/data/ExploreCampaignsResponse.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/data/Article.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/data/ArticlesEdited.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/data/Course.kt
Issue #80 
Classes updated:
- CampaignListData
- ExploreCampaignsResponse
- Article
- ArticlesEdited
- Course
> Code documenting part 4

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/presenter/ArticlesEditedPresenter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/presenter/ArticlesEditedPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/provider/ArticlesEditedProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/provider/RetrofitArticlesEditedProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/view/ArticlesEditedView.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/view/CourseArticlesEditedFragment.kt
issue #80 
Classes affected:
- ArticlesEditedPresenter
- ArticlesEditedPresenterImpl
- ArticlesEditedProvider
- RetrofitArticlesEditedProvider
- ArticlesEditedView
- CourseArticlesEditedFragment
> Code documenting 6

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/common/view/CourseDetailActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/common/view/CourseDetailView.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/RecentActivityContract.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/RecentActivityFragment.kt
Issue #80 
- RecentActivityContract
- RecentActivityFragment
- CourseDetailActivity
- CourseDetailView
> Code documenting 8

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/CourseUploadsRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/ProfileCourseListRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/adapters/StudentListRecyclerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/data/CampaignListData.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/data/Article.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/common/data/CourseDetail.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/common/view/home/CourseHomeFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/common/view/timeline/CourseTimelineFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/data/RecentActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/data/User.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/data/CourseUpload.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/data/CourseListData.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/data/MyDashboardResponse.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/data/UserData.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/view/MyDashboardFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/data/FileUsage.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/data/MediaCategory.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/data/MediaDetail.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/view/MediaDetailFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/data/ProfileDetailsResponse.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/data/ProfileResponse.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileStatsFragment.kt
code refactor removing snake_case and use gson annotations for serialization
> #118 Remove snake case from the code base 

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/RecentActivityPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/RetrofitRecentActivityProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/data/Course.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/data/RecentActivityResponse.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/data/StudentList.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/data/StudentListResponse.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/data/User.kt
Issue #80 
Classes affected:
- RecentActivityPresenterImpl
- RetrofitRecentActivityProvider
- Course
- RecentActivityResponse
- StudentList
- StudentLIstResponse
- User
> chore: Code documentation for  Recent Activity, Student List POJOs

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/data/CourseUploadList.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/data/CourseUploadResponse.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/presenter/CourseUploadsPresenter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/presenter/CourseUploadsPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/provider/CourseUploadsProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/provider/RetrofitCourseUploadsProvider.kt
#91  What this PR does
Issue #80
Classes affected
- CourseUploadList
- CourseUploadResponse
- CourseUploadsPresenter
- CourseUploadsPresenterImpl
- CourseUploadsProvider
- RetrofitCourseUploadsProvider
> chore: Code Documentation for course uploads module. 

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/presenter/StudentListPresenter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/presenter/StudentListPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/provider/RetrofitStudentListProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/provider/StudentListProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/view/StudentListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/view/StudentListView.kt
Issue related to #80 
Classes affected:
- StudentListPresenter
- StudenListPresenterImpl
- RetrofitStudentListProvider
- StudentListProvider
- StudentListFragment
- StudentListView
> chore: Code Documentation for Student List module.

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileCourseListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/settings/SettingsActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/splash/SplashActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/PresenterCallback.java
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/Progressive.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/Toaster.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/ViewPagerAdapter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/ViewUtils.kt
Classes affected
- ProfileCourseListFragment
- SettingsActivity
- SplashActivity
- PresenterCallback
- Progressive
- Toaster
- ViewPagerAdapter
- ViewUtils
> chore:Code Documentation for Profile modules and util classes

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/view/CourseUploadsFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/uploads/view/CourseUploadsView.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/data/ExploreCoursesResponse.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/presenter/CourseListPresenter.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/presenter/CourseListPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/provider/CourseListProvider.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/provider/RetrofitCourseListProvider.kt
Affected classes:
- CourseUploadsFragment
- CourseUploadsView
- ExploreCourseResponse
- CourseListPresenter
- CourseListPresenterImpl
- CourseListProvider
- RetrofitCourseListProvider
> chore:Code Documentation for course uploads and Course list

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/view/MyDashboardFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/home/ExploreFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/home/HomeActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/MediaDetailsActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/MediaDetailsContract.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/MediaDetailsPresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/RetrofitMediaDetailsProvider.kt
For issue #80 
Classes affected
- MyDashboardFragment
- ExploreFragment
- HomeActivity
- MediaDetailsActivity
- MediaDetailsContract
- MediaDetailsPresenterImpl
- RetrofitMediaDetailsProvider
> chore:Code Documentation for dashboard, explore, & Media Details modules

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/data/MediaDetailsResponse.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/data/Query.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/view/MediaDetailFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/ProfileActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/ProfileContract.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/ProfilePresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/RetrofitProfileProvider.kt
Issue related to #80 
Classes affected
- MediaDetailsResponse
- Query
- MediaDetailFragment
- ProfileActivity
- ProfileContract
- ProfilePresenterImpl
- RetrofitProfileProvider
> chore:Code Documentation for MediaDetail and Profile modules

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/CustomTabHelper.kt
Issue #80 
Class affected:
- CustomTabHelper
> chore: Code Documentation for CustomTabHelper.kt

- app/src/main/res/layout/fragment_campaign_list.xml
Changed fragment_campaign_layout.xml to constraint layout and increased bottom margin on the FAB so the whole FAB is visible (matched FAB bottom margin in fragment_my_dashboard.xml).
Before:
< add a screenshot of the UI before your change >
After:
> Addresses #139 : Changed fragment_campaign_list.xml layout to constraint layout.

- app/src/main/res/layout/fragment_my_dashboard.xml
Changed fragment_my_dashboard.xml to ConstraintLayout.
> Addresses #147: Changed fragment_my_dashboard.xml to ConstraintLayout

- app/src/main/res/layout/fragment_upload_list.xml
**What this PR does**
Changed fragment_upload_list.xml from Relative layout to Constraint layout
**Reference**
[Sub issue] #148 
**Screenshots**
User interface remains the same
> Changed fragment_upload_list.xml from Relative to Constraint layout

- app/src/main/res/layout/fragment_explore.xml
Change the fragment_explore layout to Constraint layout  issue #141
> changed fragment_explore frome linerLayout to ConstraintLayout issue #141

- app/src/main/res/layout/fragment_image_viewer.xml
> chore: Refactor fragment_image_viewer to use ConstraintLayout

- app/src/main/res/layout/item_rv_files.xml
> chore: Refactor item_rv_files to use ConstraintLayoutChanged 

- app/src/main/res/layout/include_files_media.xml
> chore: Refactor item_include_files_mediav_files to use ConstraintLayoutChanged

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/common/view/CourseDetailActivity.kt
** What this PR does**
- Changed the position of Activity and Uploads titleList on CourseDetailActivity
Before:
After:
> fix: Changed the position of the Activity and Upload titleList on CourseDetailActivity

- app/src/main/res/layout/fragment_explore.xml
> fix: removed unneccessary constraint from fragment_explore

- app/src/main/res/layout/item_rv_campaign_list.xml
> chore: changed item_rv_campaign_list to ConstraintLayout

- app/src/main/res/layout/item_rv_course_upload.xml
> chore: Changed item_rv_course_upload to ConstraintLayout

- app/src/main/res/layout/item_rv_explore_courses.xml
> chore: Changed item_rv_explore_courses to ConstraintLayout

- app/src/main/res/layout/item_rv_explore_courses_users.xml
> chore: Changed item_rv_explore_courses_users  to ConstraintLayout

- app/src/main/res/layout/item_rv_media_category.xml
> chore: Changed item_rv_media_category to ConstraintLayout

- app/src/main/res/layout/item_rv_my_dashboard.xml
> chore: Changed item_rv_my_dashboard to ConstraintLayout

- app/src/main/res/layout/item_rv_students.xml
> chore: Changed item_rv_students to ConstraintLayout

- app/src/main/res/layout/fragment_recent_activity.xml
**What this PR does**
- Changed the layout from RelativeLayout to ConstraintLAyout
**Concerns**
UI remains the same
> chore: Changed fragment_recent_activty to ConstraintLayout

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/ProfileContract.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/ProfilePresenterImpl.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileCourseListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileStatsFragment.kt
> Fix crash on profile fragment

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/view/CampaignListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/articlesedited/view/CourseArticlesEditedFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/common/view/CourseDetailActivity.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/recentactivity/RecentActivityFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/coursedetail/students/view/StudentListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/view/CourseListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/dashboard/view/MyDashboardFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/mediadetail/view/MediaDetailFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/profile/view/ProfileStatsFragment.kt
> Fixes #234

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/settings/SettingsActivity.kt
**What this PR does**
Fixes #270 
- Removed hardcoded version code and made it dynamic.
> Removed harcoded version code and made it more dynamic

- buildSrc/src/main/java/Dependencies.kt
> chore: Target SDK version increased

- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/campaign/view/CampaignListFragment.kt
- app/src/main/java/org/wikiedufoundation/wikiedudashboard/ui/courselist/view/CourseListFragment.kt
What this PR does
Fixes #280 
Fixes the search functionality in explore fragment.
> fixed search function in explore fragment

- docs/Android_App_Setup.md
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/apps-android-wikiedudashboard/blob/master/CONTRIBUTING.md#pull-request-process
Fixes #325 
Added instruction for how to set up the project for local development environment.
Before:
< add a screenshot of the UI before your change >
After:
< add a screenshot of the UI after your change >
< anything you learned that you want to share, or questions you're wondering about related to this PR >
> App setup markdown
